# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simple_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(451, 362)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.raster_map = gui.QgsMapLayerComboBox(self.tab_1)
        self.raster_map.setFilters(core.QgsMapLayerProxyModel.RasterLayer)
        self.raster_map.setObjectName("raster_map")
        self.verticalLayout_2.addWidget(self.raster_map)
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.train_vector = gui.QgsMapLayerComboBox(self.tab_1)
        self.train_vector.setFilters(core.QgsMapLayerProxyModel.HasGeometry)
        self.train_vector.setObjectName("train_vector")
        self.verticalLayout_2.addWidget(self.train_vector)
        self.label_3 = QtWidgets.QLabel(self.tab_1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.vector_class_field = gui.QgsFieldComboBox(self.tab_1)
        self.vector_class_field.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.vector_class_field.setFilters(core.QgsFieldProxyModel.Double|core.QgsFieldProxyModel.Int|core.QgsFieldProxyModel.LongLong|core.QgsFieldProxyModel.Numeric|core.QgsFieldProxyModel.String)
        self.vector_class_field.setObjectName("vector_class_field")
        self.verticalLayout_2.addWidget(self.vector_class_field)
        self.label_4 = QtWidgets.QLabel(self.tab_1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.vector_id_field = gui.QgsFieldComboBox(self.tab_1)
        self.vector_id_field.setObjectName("vector_id_field")
        self.verticalLayout_2.addWidget(self.vector_id_field)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.tab_1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.data_importer = QtWidgets.QComboBox(self.tab_2)
        self.data_importer.setObjectName("data_importer")
        self.verticalLayout.addWidget(self.data_importer)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.model = QtWidgets.QComboBox(self.tab_2)
        self.model.setObjectName("model")
        self.verticalLayout.addWidget(self.model)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget"))
        self.label.setText(_translate("DockWidget", "Raster Map"))
        self.label_2.setText(_translate("DockWidget", "Training Vectors"))
        self.label_3.setText(_translate("DockWidget", "Class Field"))
        self.label_4.setText(_translate("DockWidget", "Unique ID Field"))
        self.pushButton.setText(_translate("DockWidget", "Classify"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("DockWidget", "Classification"))
        self.label_5.setText(_translate("DockWidget", "Data Importer"))
        self.label_6.setText(_translate("DockWidget", "Model"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DockWidget", "Configuration"))

    def on_layer_change(self):
        self.vector_class_field.setFields(core.QgsFields())
        self.vector_id_field.setFields(core.QgsFields())
        if self.vector_class_field.currentField() == ''\
                and self.train_vector.currentLayer()\
                and self.train_vector.currentLayer() != 'NoneType':
            try:
                active_layer = self.train_vector.currentLayer()
                provider = active_layer.dataProvider()
                fields = provider.fields()
                list_fields_names = [field.name() for field in fields]
                self.vector_class_field.addItems(list_fields_names)
                self.vector_id_field.addItems(list_fields_names)
            except BaseException as e:
                raise e


from qgis import core
from qgis import gui
